### ISSUE TITLE
Change interface for Tech News tab 

### ISSUE THREAD

**Issue by Pinti0001** [GauravPandey123webdeveloper/TechiSpot#47]
## Hello there,
**I hope my suggestions like you.
I found one issue with tech news tab interface.
first see this tab.**

<img width="1440" alt="Screenshot 2024-03-01 at 7 44 25 PM" src="https://github.com/GauravPandey123webdeveloper/TechiSpot/assets/149884737/5fe5fa5b-6028-4218-9608-1d9dd06af8a3">

## This tab is not attractive so I want this tab to look like this.

<img width="1440" alt="Screenshot 2024-03-01 at 7 46 31 PM" src="https://github.com/GauravPandey123webdeveloper/TechiSpot/assets/149884737/3c2d1d04-008d-4330-bb16-9921ce91f7b9">

## Either solve it or assign it to someone

**Comment by AdityaJ2305** [comment]
Hi Harendra , This issue has been fixed by someone so you can closed this issue
